# Generated by Django 3.0.5 on 2020-09-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdb',
            name='text',
        ),
        migrations.RemoveField(
            model_name='postdb',
            name='title',
        ),
        migrations.AddField(
            model_name='postdb',
            name='name',
            field=models.TextField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='postdb',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
