# Generated by Django 3.0.5 on 2020-09-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200916_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdb',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
