# Generated by Django 3.0.5 on 2021-04-09 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllCourtInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_close', models.BooleanField(default=False)),
                ('range_booking_days', models.PositiveIntegerField()),
                ('payment_member_duration', models.DurationField()),
                ('payment_guest_duration', models.DurationField()),
                ('refund_duration', models.DurationField()),
                ('refund_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('num_of_creategroup', models.PositiveIntegerField()),
                ('announce', models.CharField(max_length=1000)),
                ('ads', models.CharField(max_length=500)),
                ('rules', models.CharField(max_length=1000)),
                ('qrcode', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'bbc_allcourtinfo',
            },
        ),
        migrations.CreateModel(
            name='EachCourtInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_number', models.IntegerField(unique=True)),
                ('price_normal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_ds_mem', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_ds_group', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_ds_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_ds_start', models.TimeField()),
                ('time_ds_end', models.TimeField()),
                ('is_maintain', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bbc_eachcourtinfo',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentid', models.CharField(max_length=32, unique=True)),
                ('payment_otp', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('pay', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_founded', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bbc_payment',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('is_refunded', models.BooleanField(default=False)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Payment')),
            ],
            options={
                'db_table': 'bbc_refund',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=15)),
                ('booking_datetime', models.DateTimeField()),
                ('exp_datetime', models.DateTimeField()),
                ('price_normal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_ds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_pay', models.DecimalField(decimal_places=2, max_digits=5)),
                ('payment_state', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('bookingid', models.CharField(max_length=32)),
                ('paymentid', models.CharField(max_length=32, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.EachCourtInfo')),
            ],
            options={
                'db_table': 'bbc_booking',
            },
        ),
    ]
