# Generated by Django 3.0.5 on 2020-11-22 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_number', models.IntegerField(unique=True)),
                ('price_normal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_ds_mem', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_ds_gang', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_ds_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time_ds_start', models.TimeField()),
                ('time_ds_end', models.TimeField()),
                ('maintain', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'court_detail',
            },
        ),
        migrations.CreateModel(
            name='HistoryMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('price_normal', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_ds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pay', models.DecimalField(decimal_places=2, max_digits=5)),
                ('state', models.IntegerField(default=0)),
                ('receipt', models.CharField(max_length=32)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.CourtDetail', to_field='court_number', unique=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'history_member',
            },
        ),
        migrations.CreateModel(
            name='OtherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_gap_minute', models.DecimalField(decimal_places=0, max_digits=3)),
                ('confirm_gap_minute', models.DecimalField(decimal_places=0, max_digits=3)),
                ('refund_percent', models.DecimalField(decimal_places=0, max_digits=3)),
                ('time_open', models.TimeField()),
                ('time_close', models.TimeField()),
                ('force_close', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'other_detail',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.TimeField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.CourtDetail', to_field='court_number', unique=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='RequesMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_create', models.BooleanField(default=False)),
                ('state', models.BooleanField(default=False)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'request_member',
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=20)),
                ('state', models.BooleanField(default=False)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.HistoryMember')),
            ],
            options={
                'db_table': 'refund',
            },
        ),
        migrations.CreateModel(
            name='HistoryGuess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess_name', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
                ('pay', models.DecimalField(decimal_places=2, max_digits=5)),
                ('guess_email', models.EmailField(max_length=254)),
                ('guess_tel', models.CharField(max_length=10)),
                ('receipt', models.CharField(max_length=32)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.CourtDetail', to_field='court_number', unique=True)),
            ],
            options={
                'db_table': 'history_guess',
            },
        ),
        migrations.CreateModel(
            name='HistoryGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DecimalField(decimal_places=0, max_digits=1)),
                ('time', models.TimeField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.CourtDetail', to_field='court_number', unique=True)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.Group')),
            ],
            options={
                'db_table': 'history_group',
            },
        ),
        migrations.CreateModel(
            name='ConfirmPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref1', models.DecimalField(decimal_places=0, max_digits=20)),
                ('ref2', models.DecimalField(decimal_places=0, max_digits=20)),
                ('pay', models.DecimalField(decimal_places=2, max_digits=5)),
                ('state', models.BooleanField(default=False)),
                ('is_found', models.BooleanField(default=False)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.HistoryMember')),
            ],
            options={
                'db_table': 'confirm_pay',
            },
        ),
    ]
