# Generated by Django 3.0.5 on 2020-12-27 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymember',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_member', to='member.Member'),
        ),
        migrations.AddField(
            model_name='historyguest',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.CourtDetail', to_field='court_number'),
        ),
        migrations.AddField(
            model_name='historygroup',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.CourtDetail', to_field='court_number'),
        ),
        migrations.AddField(
            model_name='historygroup',
            name='header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_group', to='member.Group'),
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='history_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.HistoryGroup'),
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='history_guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.HistoryGuest'),
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='history_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.HistoryMember'),
        ),
    ]
