# Generated by Django 3.0.5 on 2020-12-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfirmPay',
            new_name='CheckPayment',
        ),
        migrations.RenameModel(
            old_name='HistoryGuess',
            new_name='HistoryGuest',
        ),
        migrations.RenameField(
            model_name='historyguest',
            old_name='guess_email',
            new_name='guest_email',
        ),
        migrations.RenameField(
            model_name='historyguest',
            old_name='guess_name',
            new_name='guest_name',
        ),
        migrations.RenameField(
            model_name='historyguest',
            old_name='guess_tel',
            new_name='guest_tel',
        ),
        migrations.AlterModelTable(
            name='checkpayment',
            table='check_payment',
        ),
        migrations.AlterModelTable(
            name='historyguest',
            table='history_guest',
        ),
    ]
