# Generated by Django 3.0.5 on 2021-03-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20201228_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='time_out',
            field=models.TimeField(default=None),
        ),
    ]
