# Generated by Django 3.0.5 on 2021-03-14 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_status_time_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_num', to='booking.CourtDetail', to_field='court_number'),
        ),
    ]
