# Generated by Django 3.0.5 on 2021-04-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210409_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourtinfo',
            name='range_booking_days',
            field=models.DurationField(),
        ),
    ]
