# Generated by Django 3.0.5 on 2021-04-09 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20210409_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcourtinfo',
            old_name='range_booking_days',
            new_name='range_booking',
        ),
    ]
