# Generated by Django 3.0.5 on 2021-03-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_historyguest_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='receipt',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
