# Generated by Django 3.0.5 on 2020-12-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20201220_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesmember',
            name='action',
            field=models.IntegerField(default=None),
        ),
    ]
