# Generated by Django 3.0.5 on 2020-12-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20201224_0037'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequesMember',
        ),
    ]
