# Generated by Django 3.0.5 on 2021-04-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210409_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_otp',
        ),
        migrations.AddField(
            model_name='allcourtinfo',
            name='groupbooking_lastmonth_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='allcourtinfo',
            name='payment_group_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_pic',
            field=models.ImageField(null=True, upload_to='payment_pic'),
        ),
        migrations.AlterField(
            model_name='allcourtinfo',
            name='refund_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
