# Generated by Django 3.0.5 on 2021-03-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_status_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherdetail',
            name='confirm_gap_minute',
        ),
        migrations.AddField(
            model_name='otherdetail',
            name='annouce',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='otherdetail',
            name='confirm_gap_minute_guest',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='otherdetail',
            name='confirm_gap_minute_member',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='otherdetail',
            name='number_of_member_create_group',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='otherdetail',
            name='refund_gap_minute',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='otherdetail',
            name='refund_percent',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
