# Generated by Django 3.0.5 on 2021-03-29 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20210329_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otherdetail',
            old_name='confirm_gap_minute_guest',
            new_name='confirm_gap_min_guest',
        ),
        migrations.RenameField(
            model_name='otherdetail',
            old_name='confirm_gap_minute_member',
            new_name='confirm_gap_min_member',
        ),
        migrations.RenameField(
            model_name='otherdetail',
            old_name='number_of_member_create_group',
            new_name='n_member_creategroup',
        ),
        migrations.RenameField(
            model_name='otherdetail',
            old_name='refund_gap_minute',
            new_name='refund_gap_min',
        ),
    ]
