# Generated by Django 3.0.5 on 2021-04-22 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20210423_0412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcourtinfo',
            old_name='groupbooking_lastmonth_duration',
            new_name='groupbooking_lastmonth_day',
        ),
    ]
