# Generated by Django 3.0.5 on 2021-04-26 19:21

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_auto_20210418_2207'),
        ('booking', '0014_auto_20210427_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='group',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Group'),
        ),
        migrations.AddField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='court',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='booking.EachCourtInfo'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='group',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Group'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 2, 21, 48, 311491, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 2, 21, 48, 311491, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='booking.Payment'),
        ),
        migrations.AlterField(
            model_name='refund',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 27, 2, 21, 48, 312488, tzinfo=utc)),
        ),
    ]
