# Generated by Django 3.0.5 on 2021-05-04 03:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20210502_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='exp_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 10, 41, 29, 65271, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 10, 41, 29, 66300, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='refund',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 10, 41, 29, 66300, tzinfo=utc)),
        ),
    ]
