# Generated by Django 3.0.5 on 2021-05-04 20:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_auto_20210504_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingid',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 3, 4, 41, 95995, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 3, 4, 41, 96993, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='refund',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 3, 4, 41, 96993, tzinfo=utc)),
        ),
    ]
