# Generated by Django 3.0.5 on 2021-05-06 14:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_auto_20210502_2119'),
        ('booking', '0020_auto_20210505_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcourtinfo',
            name='qrcode',
        ),
        migrations.AddField(
            model_name='allcourtinfo',
            name='bank_acc_id',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='allcourtinfo',
            name='bank_acc_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='member',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 21, 7, 11, 118702, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 21, 7, 11, 119402, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='refund',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 21, 7, 11, 119402, tzinfo=utc)),
        ),
    ]
