# Generated by Django 3.0.5 on 2021-05-08 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0021_auto_20210506_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='detail',
            new_name='bank_acc_id',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='payment',
        ),
        migrations.AddField(
            model_name='refund',
            name='bank_acc_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='refundid',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(
                2021, 5, 8, 19, 8, 24, 372057, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(
                2021, 5, 8, 19, 8, 24, 373052, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='refund',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(
                2021, 5, 8, 19, 8, 24, 374085, tzinfo=utc)),
        ),
    ]
