# Generated by Django 3.0.5 on 2021-05-08 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0023_auto_20210508_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refundid',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 19, 22, 28, 607511, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 19, 22, 28, 608508, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='refund',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 19, 22, 28, 608508, tzinfo=utc)),
        ),
    ]
