# Generated by Django 3.0.5 on 2021-05-14 09:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_auto_20210502_2119'),
        ('booking', '0024_auto_20210508_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='group',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Group'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 16, 24, 52, 681458, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 16, 24, 52, 682457, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='refund',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 16, 24, 52, 683454, tzinfo=utc)),
        ),
    ]
