# Generated by Django 3.0.5 on 2021-05-14 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0025_auto_20210514_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourtinfo',
            name='refund_group_duration',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='allcourtinfo',
            name='refund_group_percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 16, 31, 33, 16700, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 16, 31, 33, 16700, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='refund',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 16, 31, 33, 17695, tzinfo=utc)),
        ),
    ]
