# Generated by Django 3.0.5 on 2021-05-14 09:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0026_auto_20210514_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcourtinfo',
            name='refund_group_duration',
        ),
        migrations.AddField(
            model_name='allcourtinfo',
            name='refund_group_day',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 16, 32, 51, 265881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 16, 32, 51, 265881, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='refund',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 14, 16, 32, 51, 266880, tzinfo=utc)),
        ),
    ]
