# Generated by Django 3.0.5 on 2021-05-15 21:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0027_auto_20210514_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcourtinfo',
            old_name='refund_duration',
            new_name='refund_member_duration',
        ),
        migrations.RenameField(
            model_name='allcourtinfo',
            old_name='refund_percent',
            new_name='refund_member_percent',
        ),
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 4, 41, 30, 879207, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 4, 41, 30, 880205, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='refund',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 16, 4, 41, 30, 880205, tzinfo=utc)),
        ),
    ]
