# Generated by Django 3.0.5 on 2021-05-18 18:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0029_auto_20210519_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcourtinfo',
            old_name='ads',
            new_name='contacts',
        ),
        migrations.RenameField(
            model_name='allcourtinfo',
            old_name='refund_duration',
            new_name='refund_member_duration',
        ),
        migrations.RenameField(
            model_name='allcourtinfo',
            old_name='refund_percent',
            new_name='refund_member_percent',
        ),
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 1, 58, 14, 491117, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 1, 58, 14, 491117, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='refund',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 19, 1, 58, 14, 492112, tzinfo=utc)),
        ),
    ]
