# Generated by Django 3.0.5 on 2021-05-24 18:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_auto_20210519_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourtinfo',
            name='fes_date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='allcourtinfo',
            name='fes_date_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='allcourtinfo',
            name='payment_member_duration_fes',
            field=models.DurationField(null=True),
        ),
        migrations.AddField(
            model_name='allcourtinfo',
            name='refund_member_duration_fes',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 1, 51, 26, 310076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 1, 51, 26, 311076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='refund',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 1, 51, 26, 311076, tzinfo=utc)),
        ),
    ]
