# Generated by Django 3.0.5 on 2021-05-24 19:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0037_auto_20210525_0239'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='refund_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 2, 40, 51, 827040, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 2, 40, 51, 827040, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 2, 40, 51, 827040, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='refund',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 2, 40, 51, 828037, tzinfo=utc)),
        ),
    ]
