# Generated by Django 3.0.5 on 2021-05-24 21:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0039_auto_20210525_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='refund_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 4, 11, 33, 672869, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 4, 11, 33, 672869, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 4, 11, 33, 673904, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='refund',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 25, 4, 11, 33, 674904, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='allcourtinfo',
            table='bcb_allcourtinfo',
        ),
        migrations.AlterModelTable(
            name='booking',
            table='bcb_booking',
        ),
        migrations.AlterModelTable(
            name='eachcourtinfo',
            table='bcb_eachcourtinfo',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='bcb_payment',
        ),
        migrations.AlterModelTable(
            name='refund',
            table='bcb_refund',
        ),
    ]
