# Generated by Django 3.0.5 on 2020-12-27 20:17

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True)),
                ('outside_detail', models.CharField(max_length=500)),
                ('inside_detail', models.CharField(max_length=500)),
                ('is_continue', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                  parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tel', models.CharField(max_length=10)),
                ('birthday', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10)),
                ('group_role', models.IntegerField(null=True)),
                ('test', models.CharField(max_length=5, null=True)),
                ('mygroup', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Group', to_field='group_name')),
            ],
            options={
                'db_table': 'member',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RequestMember',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(default=None)),
                ('state', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('header', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='member.Group')),
                ('member', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'request_member',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(default=None)),
                ('state', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               related_name='receiver', to='member.Member', to_field='username')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             related_name='sender', to='member.Member', to_field='username')),
            ],
            options={
                'db_table': 'request',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('on_court', models.BooleanField(default=False)),
                ('group_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='group', to='member.Group', to_field='group_name')),
                ('member', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='member.Member')),
            ],
            options={
                'db_table': 'group_member',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='header',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='member.Member'),
        ),
    ]
