# Generated by Django 3.0.5 on 2021-03-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='group_role',
        ),
        migrations.RemoveField(
            model_name='member',
            name='mygroup',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='role',
            field=models.CharField(default='m', max_length=1),
        ),
    ]
