# Generated by Django 3.0.5 on 2021-04-11 12:50

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='count',
        ),
        migrations.AddField(
            model_name='group',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='virtualid',
            field=models.CharField(default=member.models.Member.randomint),
        ),
    ]
