# Generated by Django 3.0.5 on 2021-03-22 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210322_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='test',
        ),
    ]
