# Generated by Django 3.0.5 on 2021-04-14 16:18

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20210414_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='virtualid',
            field=models.CharField(
                default=member.models.Member.randomint, unique=True),
        ),
    ]
