# Generated by Django 3.0.5 on 2021-03-27 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_remove_member_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='group_name',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='member.Group'),
        ),
    ]
