# Generated by Django 3.0.5 on 2021-03-27 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20210328_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Group'),
        ),
        migrations.DeleteModel(
            name='RequestMember',
        ),
    ]
