# Generated by Django 3.0.5 on 2020-12-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_requesmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='group_member',
            field=models.BooleanField(default=False),
        ),
    ]
