# Generated by Django 3.0.5 on 2021-03-27 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_requestmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='group',
        ),
    ]
