# Generated by Django 3.0.5 on 2021-03-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_request_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='role',
        ),
    ]
