# Generated by Django 3.0.5 on 2020-12-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20201224_0245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequesMember',
            new_name='RequestMember',
        ),
    ]
