# Generated by Django 3.0.5 on 2021-04-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_auto_20210418_0504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='inside_detail',
            new_name='announce',
        ),
        migrations.RemoveField(
            model_name='group',
            name='outside_detail',
        ),
    ]
