# Generated by Django 3.0.5 on 2021-03-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20210329_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='role',
            field=models.CharField(default='', max_length=1),
        ),
    ]
