# Generated by Django 3.0.5 on 2021-05-02 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0011_auto_20210418_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, db_constraint=False, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
