# Generated by Django 3.0.5 on 2020-12-24 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_requestmember_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(default=None)),
                ('state', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='member.Member', to_field='username')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='member.Member', to_field='username')),
            ],
            options={
                'db_table': 'request',
            },
        ),
    ]
