# Generated by Django 3.0.5 on 2020-12-24 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group',
            new_name='group_name',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='group',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.Group', to_field='group_name'),
        ),
    ]
