# Generated by Django 3.0.5 on 2021-05-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_auto_20210502_2119'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='bcb_group',
        ),
        migrations.AlterModelTable(
            name='groupmember',
            table='bcb_groupmember',
        ),
        migrations.AlterModelTable(
            name='member',
            table='bcb_member',
        ),
        migrations.AlterModelTable(
            name='request',
            table='bcb_request',
        ),
    ]
