# Generated by Django 3.0.5 on 2020-12-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20201125_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
