# Generated by Django 3.0.5 on 2020-12-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_member_group_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='group_member',
        ),
        migrations.AddField(
            model_name='member',
            name='group_role',
            field=models.IntegerField(null=True),
        ),
    ]
