# Generated by Django 3.0.5 on 2020-12-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20201224_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='group',
        ),
    ]
