# Generated by Django 3.0.5 on 2020-12-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_auto_20201224_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmember',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
