# Generated by Django 3.0.5 on 2020-12-26 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_auto_20201225_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='group_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='member.Group', to_field='group_name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mygroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Group', to_field='group_name'),
        ),
    ]
