# Generated by Django 3.0.5 on 2020-12-27 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_auto_20201227_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='mygroup',
            new_name='mygroup2',
        ),
    ]
