# Generated by Django 3.0.5 on 2020-12-27 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_auto_20201228_0223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='group_role',
            new_name='group_role2',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='mygroup2',
            new_name='mygroup',
        ),
    ]
