# Generated by Django 3.0.5 on 2020-12-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_auto_20201228_0242'),
    ]

    operations = [
    ]
