# Generated by Django 3.0.5 on 2020-12-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_auto_20201228_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='test',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
