# Generated by Django 3.0.5 on 2020-12-27 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0020_member_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='group_role22',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='mygroup22',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Group', to_field='group_name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mygroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test', to='member.Group'),
        ),
    ]
