# Generated by Django 3.0.5 on 2020-12-27 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0022_auto_20201228_0253'),
    ]

    operations = [

    ]
