# Generated by Django 3.0.5 on 2020-12-27 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0023_auto_20201228_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='group_role',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='mygroup',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.Group', to_field='group_name'),
        ),
    ]
