# Generated by Django 3.0.5 on 2020-12-16 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20201210_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.CourtDetail'),
        ),
    ]
