# Generated by Django 3.0.5 on 2020-12-16 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20201216_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historygroup',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.CourtDetail'),
        ),
        migrations.AlterField(
            model_name='historyguest',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.CourtDetail'),
        ),
        migrations.AlterField(
            model_name='historymember',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.CourtDetail'),
        ),
    ]
