# Generated by Django 3.0.5 on 2020-12-16 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20201216_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkpayment',
            old_name='pay',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='checkpayment',
            old_name='ref1',
            new_name='transection',
        ),
        migrations.RemoveField(
            model_name='checkpayment',
            name='history',
        ),
        migrations.RemoveField(
            model_name='checkpayment',
            name='ref2',
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='history_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.HistoryGroup'),
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='history_guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.HistoryGuest'),
        ),
        migrations.AddField(
            model_name='checkpayment',
            name='history_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.HistoryMember'),
        ),
    ]
