# Generated by Django 3.0.5 on 2020-12-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20201216_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesmember',
            name='is_create',
        ),
        migrations.AddField(
            model_name='requesmember',
            name='action',
            field=models.IntegerField(default=0),
        ),
    ]
