# Generated by Django 3.0.5 on 2020-12-24 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_delete_requesmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='historygroup',
            name='pay',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historygroup',
            name='price_normal',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historygroup',
            name='receipt',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='historygroup',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historygroup',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historygroup',
            name='total_ds',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='historyguest',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historymember',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historygroup',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.CourtDetail', to_field='court_number'),
        ),
        migrations.AlterField(
            model_name='historyguest',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.CourtDetail', to_field='court_number'),
        ),
        migrations.AlterField(
            model_name='historyguest',
            name='pay',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='historyguest',
            name='receipt',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historymember',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.CourtDetail', to_field='court_number'),
        ),
        migrations.AlterField(
            model_name='historymember',
            name='pay',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='historymember',
            name='price_normal',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='historymember',
            name='receipt',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historymember',
            name='total_ds',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
